<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <EnableRazorRuntime>false</EnableRazorRuntime>

    <StaticWebAssetBasePath>.</StaticWebAssetBasePath>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Velvet.Core" Version="0.1.0" />
    <PackageReference Include="Velvet.Graphics.WebGL" Version="0.1.0" />
    <PackageReference Include="Velvet.Hosting.Web" Version="0.1.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all" />
  </ItemGroup>

</Project>